services:
  # Frontend React Application
  - type: web
    name: seedsync-frontend
    env: node
    rootDir: rando
    buildCommand: npm install && npm run build
    startCommand: serve -s dist -l $PORT
    envVars:
      - key: NODE_ENV
        value: development
      - key: VITE_API_BASE_URL
        value: https://seedsync-backend.onrender.com
    healthCheckPath: /
    autoDeploy: true
    branch: master
    plan: free
    region: oregon

  # Backend FastAPI Application
  - type: web
    name: seedsync-backend
    env: docker
    dockerfilePath: rando/backend/Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: CORS_ORIGINS
        value: https://seedsync-frontend.onrender.com
    healthCheckPath: /
    autoDeploy: true
    branch: master
    buildFilter:
      paths:
        - rando/backend/** 