# services:
#   # Frontend React Application
#   - type: web
#     name: seedsync-frontend
#     env: node
#     rootDir: rando
#     buildCommand: npm install && npm run build
#     startCommand: serve -s dist -l $PORT
#     envVars:
#       - key: NODE_ENV
#         value: development
#       - key: VITE_API_BASE_URL
#         value: https://mock-backend.onrender.com
#     healthCheckPath: /
#     autoDeploy: true
#     branch: master
#     plan: free
#     region: oregon

services:
  - type: web
    name: mock-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
    branch: master
    plan: free
    region: oregon 